### YamlMime:PowershellCmdlet
summary: |-
  Modifies the configuration of a remote access role.
module: RemoteAccess
notes: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#RemoteAccessConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-RemoteAccessConfiguration
  href: ./Get-RemoteAccessConfiguration.yml
syntaxes:
- >-
  Set-RemoteAccessConfiguration [-Configuration] <CimInstance> [-RestartServiceIfRequired] [-PassThru]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [<CommonParameters>]
examples:
- title: 'Example 1: Modify remote access configuration'
  code: |-
    PS C:\>Set-RemoteAccessConfiguration
  description: |-
    This command modifies the remote access configuration for a computer.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: Configuration
  isRequired: true
  description: |+
    Specifies a remote access configuration object.
    To obtain a configuration object, use the **Get-CimInstance** cmdlet.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: RestartServiceIfRequired
  description: |+
    Indicates that the Remote Access service restarts if required by any configuration changes.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShellÂ® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: RemoteAccess.Set-RemoteAccessConfiguration
name: Set-RemoteAccessConfiguration
description: |-
  The **Set-RemoteAccessConfiguration** cmdlet modifies a remote access role by using a Windows PowerShell object.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: PS_RemoteAccessConfiguration_v1.0.cdxml-help.xml
  Module Name: RemoteAccess
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/remoteaccess/set-remoteaccessconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-RemoteAccessConfiguration
