### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the SMB server configuration.
module: SmbShare
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root/Microsoft/Windows/SMB/MSFT_SmbServerConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The **MSFT_SmbServerConfiguration** object represents the configuration of the SMB server.
links:
- text: Set-SmbServerConfiguration
  href: ./Set-SmbServerConfiguration.yml
syntaxes:
- >-
  Get-SmbServerConfiguration [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Get SMB server configuration'
  code: |-
    PS C:\>Get-SmbServerConfiguration
    AnnounceServer                  : False 
    AsynchronousCredits             : 64 
    AutoShareServer                 : True 
    AutoShareWorkstation            : True 
    CachedOpenLimit                 : 5 
    AnnounceComment                 : 
    EnableDownlevelTimewarp         : False 
    EnableLeasing                   : True 
    EnableMultiChannel              : True 
    EnableStrictNameChecking        : True 
    AutoDisconnectTimeout           : 0 
    DurableHandleV2TimeoutInSeconds : 30 
    EnableAuthenticateUserSharing   : False 
    EnableForcedLogoff              : True 
    EnableOplocks                   : True 
    EnableSecuritySignature         : False 
    ServerHidden                    : True 
    IrpStackSize                    : 15 
    KeepAliveTime                   : 2 
    MaxChannelPerSession            : 32 
    MaxMpxCount                     : 50 
    MaxSessionPerConnection         : 16384 
    MaxThreadsPerQueue              : 20 
    MaxWorkItems                    : 1 
    NullSessionPipes                : 
    NullSessionShares               : 
    OplockBreakWait                 : 35 
    PendingClientTimeoutInSeconds   : 120 
    RequireSecuritySignature        : False 
    EnableSMB1Protocol              : True 
    EnableSMB2Protocol              : True 
    Smb2CreditsMax                  : 2048 
    Smb2CreditsMin                  : 128 
    SmbServerNameHardeningLevel     : 0 
    TreatHostAsStableStorage        : False 
    ValidateAliasNotCircular        : True 
    ValidateShareScope              : True 
    ValidateShareScopeNotAliased    : True 
    ValidateTargetName              : True 
    EncryptData                     : False 
    RejectUnencryptedAccess         : True
  description: |-
    This command retrieves the SMB server configuration.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShellÂ® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: SmbShare.Get-SmbServerConfiguration
name: Get-SmbServerConfiguration
description: |-
  The **Get-SmbServerConfiguration** cmdlet retrieves the Server Message Block (SMB) server configuration.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: SmbServerConfiguration.cdxml-help.xml
  Module Name: SmbShare
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/smbshare/get-smbserverconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-SmbServerConfiguration
