### YamlMime:PowershellCmdlet
summary: |-
  Removes configuration settings from a configuration location.
module: WebAdministration
notes: ""
links:
- text: Add-WebConfiguration
  href: ./Add-WebConfiguration.yml
- text: Get-WebConfiguration
  href: ./Get-WebConfiguration.yml
- text: Restore-WebConfiguration
  href: ./Restore-WebConfiguration.yml
- text: Set-WebConfiguration
  href: ./Set-WebConfiguration.yml
syntaxes:
- >-
  Clear-WebConfiguration [-Clr <String>] [-Force] [-Location <String[]>] [-Filter] <String[]>

   [[-PSPath] <String[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Remove ASP configuration on the root node'
  code: |-
    C:\PS> Clear-WebConfiguration -Filter "/system.webServer/asp" -PSPath "IIS:\"
  description: |-
    This command removes the \<asp\> section from the root node.
  summary: ""
- title: 'Example 2: Remove a configuration property from the root node'
  code: |-
    C:\PS> Clear-WebConfiguration -Filter "/system.webServer/asp/@lcid" -PSPath "IIS:\"
  description: |-
    This command removes the **lcid** property from the IIS configuration root node.
  summary: ""
- title: 'Example 3: Remove ASP configuration from the site node'
  code: |-
    IIS:\> Clear-WebConfiguration -Filter "/system.webServer/asp" -PSPath "IIS:\sites\Default Web Site"
  description: |-
    This command removes the \<asp\> section from the IIS configuration node for the default website.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Clr
  description: |+
    Specifies the version of the .NET Framework in the form vn.n, such as v4.0 or v2.0.
    The default is v4.0.
    Specify this parameter only when the *PSPath* parameter is set to either Machine or Machine/Webroot.
    If *PSPath* is not set to one of these values and the *Clr* parameter is set, Windows PowerShellÂ® ignores the value of *Clr* and returns a warning.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Filter
  isRequired: true
  description: |+
    Specifies the IIS configuration section or an XPath query that returns a configuration element.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the specified configuration to be cleared.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Location
  description: |+
    Specifies the location of the configuration setting.
    Location tags are frequently used for configuration settings that must be set more precisely than per application or per virtual directory.
    For example, a setting for a particular file or directory could use a location tag.
    Location tags are also used if a particular section is locked.
    In such an instance, the configuration system would have to use a location tag in one of the parent configuration files.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This path can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in the format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Clear-WebConfiguration
name: Clear-WebConfiguration
description: |-
  The **Clear-WebConfiguration** cmdlet removes configuration settings from the specified configuration location.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/clear-webconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Clear-WebConfiguration
