### YamlMime:PowershellCmdlet
summary: |-
  Gets an IIS configuration property at a path.
module: WebAdministration
notes: ""
inputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-WebConfigurationProperty
  href: ./Add-WebConfigurationProperty.yml
- text: Get-WebConfiguration
  href: ./Get-WebConfiguration.yml
- text: Remove-WebConfigurationProperty
  href: ./Remove-WebConfigurationProperty.yml
- text: Set-WebConfigurationProperty
  href: ./Set-WebConfigurationProperty.yml
syntaxes:
- >-
  Get-WebConfigurationProperty -Name <String[]> [-Recurse] [-Clr <String>] [-Location <String[]>]

   [-Filter] <String[]> [[-PSPath] <String[]>] [<CommonParameters>]
examples:
- title: 'Example 1: Return the default documents for the default website'
  code: |-
    C:\PS> Get-WebConfigurationProperty -Filter "//defaultDocument/files/add" -PSPath "IIS:\Sites\Default Web Site" -Name "value" | select value

    Default.htm
    Default.asp
    Index.htm
    Index.html
    Iisstart.htm
    Default.aspx
  description: |-
    This command returns a list of the default documents associated with the default website.
  summary: ""
- title: 'Example 2: Show handlers mapped to Aspnet_isapi.dll'
  code: |-
    C:\PS> Get-WebConfigurationProperty -Filter "//handlers" -PSPath "IIS:\sites\Default Web Site" -Name Collection[scriptProcessor="*aspnet_isapi.dll"] | select path,name
  description: |-
    This command gets the handlers mapped to aspnet_isapi.dll.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Clr
  description: |+
    Specifies the version of the .NET Framework in the form vn.n, such as v4.0 or v2.0.
    The default is v4.0.
    Specify this parameter only when the *PSPath* parameter is set to either Machine or Machine/Webroot.
    If *PSPath* is not set to one of these values and the *Clr* parameter is set, Windows PowerShellÂ® ignores the value of *Clr* and returns a warning.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Filter
  isRequired: true
  description: |+
    Specifies the IIS configuration section or an XPath query that returns a configuration element.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Location
  description: |+
    Specifies the location of the configuration setting.
    Location tags are frequently used for configuration settings that must be set more precisely than per application or per virtual directory.
    For example, a setting for a particular file or directory could use a location tag.
    Location tags are also used if a particular section is locked.
    In such an instance, the configuration system would have to use a location tag in one of the parent configuration files.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the property to get.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This path can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in the format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Recurse
  description: |+
    Indicates that the cmdlet returns the properties of nodes contained within the hierarchy of the specified node.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: WebAdministration.Get-WebConfigurationProperty
name: Get-WebConfigurationProperty
description: |-
  The **Get-WebConfigurationProperty** cmdlet gets an Internet Information Services (IIS) configuration property at the specified path.
  This cmdlet is similar to the Get-WebConfiguration cmdlet, but the current cmdlet supports globbing, or wildcards.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/get-webconfigurationproperty?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-WebConfigurationProperty
