### YamlMime:PowershellCmdlet
summary: |-
  Imports the custom configuration for an authentication provider.
module: ADFS
notes: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Export-AdfsAuthenticationProviderConfigurationData
  href: ./Export-AdfsAuthenticationProviderConfigurationData.yml
syntaxes:
- >-
  Import-AdfsAuthenticationProviderConfigurationData -Name <String> -FilePath <String> [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Import authentication provider configuration data'
  code: |-
    PS C:\> Import-AdfsAuthenticationProviderConfigurationData -Name "ContosoExternalAuthProvider" -FilePath "C:\share\test.txt"
  description: |-
    This command imports the authentication provider configuration data.
    This command also overwrites existing configuration data for the specified authentication provider with the data from the file.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FilePath
  isRequired: true
  description: |+
    Specifies a file path.
    The cmdlet imports the configuration data from a file that you specify.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the authentication provider to import.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Import-AdfsAuthenticationProviderConfigurationData
name: Import-AdfsAuthenticationProviderConfigurationData
description: |-
  The **Import-AdfsAuthenticationProviderConfigurationData** cmdlet imports custom configuration for an authentication provider from a file.
  Before you use this cmdlet, verify that the external authentication provider supports a custom configuration.

  Use this cmdlet when the information specific to the authentication provider changes after you initially register the authentication provider.
  In some situations, the security key to access the authentication service can change and you must update the information in the Active Directory Federation Services (AD FS) configuration store for the authentication provider to function correctly.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/import-adfsauthenticationproviderconfigurationdata?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Import-AdfsAuthenticationProviderConfigurationData
