### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the NAT64 configuration of a computer.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetNatTransitionConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.


    The **MSFT_NetNatTransitionConfiguration** object contains NAT64 configuration information.
links:
- text: Disable-NetNatTransitionConfiguration
  href: ./Disable-NetNatTransitionConfiguration.yml
- text: Enable-NetNatTransitionConfiguration
  href: ./Enable-NetNatTransitionConfiguration.yml
- text: Get-NetNatTransitionMonitoring
  href: ./Get-NetNatTransitionMonitoring.yml
- text: New-NetNatTransitionConfiguration
  href: ./New-NetNatTransitionConfiguration.yml
- text: Remove-NetNatTransitionConfiguration
  href: ./Remove-NetNatTransitionConfiguration.yml
- text: Set-NetNatTransitionConfiguration
  href: ./Set-NetNatTransitionConfiguration.yml
syntaxes:
- >-
  Get-NetNatTransitionConfiguration [-InstanceName <String[]>] [-PolicyStore <PolicyStore[]>]

   [-Adapter <CimInstance>] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [<CommonParameters>]
examples:
- title: 'Example 1: Get the NAT64 configuration'
  code: |-
    PS C:\>Get-NetNatTransitionConfiguration
  description: |-
    This command retrieves the NAT64 configuration of a computer.
  summary: ""
parameters:
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: Adapter
  description: |+
    Specifies the network adapter from which to retrieve the configuration information.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InstanceName
  description: |+
    Specifies the instance of the NAT64 for which the configuration is being retrieved.
    If this parameter is not specified, then the configuration for all of the instances of NAT64 are retrieved.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PolicyStore" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PolicyStore
  description: |+
    Specifies from which policy store the NAT64 configuration is retrieved.
    The acceptable values for this parameter are: Persistent and Active.
    If this parameter is not specified, then the cmdlet operates on both active and persistent stores.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Store
  parameterValueGroup: PersistentStore, ActiveStore
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShellÂ® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkTransition.Get-NetNatTransitionConfiguration
name: Get-NetNatTransitionConfiguration
description: |-
  The **Get-NetNatTransitionConfiguration** cmdlet retrieves the NAT64 configuration of a computer.
  NAT64 is described in [RFC 6146](http://tools.ietf.org/html/rfc6147).
  NAT64 allows IPv6-only clients to contact IPv4 servers using unicast UDP, TCP, or ICMP.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NetNatTransitionConfiguration.cdxml-help.xml
  Module Name: NetworkTransition
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networktransition/get-netnattransitionconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-NetNatTransitionConfiguration
