### YamlMime:PowershellCmdlet
summary: |-
  Installs the required role services for session-based desktop deployment.
module: RDMgmt
notes: ""
outputs:
- name: <xref href="Null" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-RDSessionDeployment [-ConnectionBroker] <String> [-SessionHost] <String[]> [[-WebAccessServer] <String>]

   [<CommonParameters>]
examples:
- title: 'Example 1: Install role services for a session deployment'
  code: |-
    PS C:\> New-RDSessionDeployment -ConnectionBroker "RDCB.Contoso.com" -WebAccessServer "RDWA.Contoso.com" -SessionHost "RDSH01.Contoso.com"
  description: |-
    This command installs Remote Desktop role services on specified servers.
    The command installs an RD Connection Broker role service on the server named RDCB.Contoso.com.
    The command installs an RD Web Access role service on the server named RDWA.Contoso.com.
    The command installs the RD Session Host role service on the server named RDSH01.Contoso.com.
  summary: ""
- title: 'Example 2: Install role services that include multiple RD Session Host servers'
  code: |-
    PS C:\> New-RDSessionDeployment -ConnectionBroker "RDCB.Contoso.com" -WebAccessServer "RDWA.Contoso.com" -SessionHost @("RDSH01.Contoso.com","RDSH02.Contoso.com")
  description: |-
    This command installs Remote Desktop role services on specified servers.
    The command installs an RD Connection Broker role service on the server named RDCB.Contoso.com.
    The command installs an RD Web Access role service on the server named RDWA.Contoso.com.
    The command installs the RD Session Host role service on two servers, named RDSH01.Contoso.com and RDSH02.Contoso.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectionBroker
  isRequired: true
  description: |+
    Specifies the FQDN of a server to host the RD Connection Broker role service.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SessionHost
  isRequired: true
  description: |+
    Specifies an array of the FQDNs of servers to host the RD Session Host role service.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: WebAccessServer
  description: |+
    Specifies the FQDN of a server to host the RD Web Access role service.

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
uid: RDMgmt.New-RDSessionDeployment
name: New-RDSessionDeployment
description: |-
  The **New-RDSessionDeployment** cmdlet installs role services required for the Virtual Desktop Infrastructure (VDI) to create a Remote Desktop Services (RDS) session-based Remote Desktop deployment.
  A session-based deployment allows users to connect to session collections that include published Windows Server 2012 RemoteApp programs and session-based desktops.

  Specify the fully qualified domain names (FQDN) for servers to host a Remote Desktop Connection Broker (RD Connection Broker) role service, a Remote Desktop Web Access (RD Web Access) role service, and one or more instances of the Remote Desktop Session Host (RD Session Host) role service.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: RemoteDesktop.psm1-help.xml
  Module Name: RDMgmt
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/rdmgmt/new-rdsessiondeployment?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: New-RDSessionDeployment
