### YamlMime:PowershellCmdlet
summary: |-
  Changes configuration settings for a virtual desktop collection.
module: RDMgmt
notes: ""
outputs:
- name: <xref href="Null" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-RDVirtualDesktopCollectionConfiguration
  href: ./Get-RDVirtualDesktopCollectionConfiguration.yml
- text: Get-RDVirtualDesktopCollection
  href: ./Get-RDVirtualDesktopCollection.yml
syntaxes:
- >-
  Set-RDVirtualDesktopCollectionConfiguration [-CollectionName] <String> [-CollectionDescription <String>]

   [-ClientDeviceRedirectionOptions <RDClientDeviceRedirectionOptions>] [-RedirectAllMonitors <Boolean>]

   [-RedirectClientPrinter <Boolean>] [-SaveDelayMinutes <Int32>] [-UserGroups <String[]>]

   [-AutoAssignPersonalVirtualDesktopToUser <Boolean>] [-GrantAdministrativePrivilege <Boolean>]

   [-CustomRdpProperty <String>] [-ConnectionBroker <String>] [<CommonParameters>]
- >-
  Set-RDVirtualDesktopCollectionConfiguration [-CollectionName] <String> [-DisableUserProfileDisks]

   [-ConnectionBroker <String>] [<CommonParameters>]
- >-
  Set-RDVirtualDesktopCollectionConfiguration [-CollectionName] <String> [-EnableUserProfileDisks]

   [-IncludeFolderPath <String[]>] [-ExcludeFolderPath <String[]>] [-IncludeFilePath <String[]>]

   [-ExcludeFilePath <String[]>] -MaxUserProfileDiskSizeGB <Int32> -DiskPath <String>

   [-ConnectionBroker <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Change the save delay setting for a virtual desktop collection'
  code: |-
    PS C:\> Set-RDVirtualDesktopCollectionConfiguration -ConnectionBroker "rdcb.contoso.com" -CollectionName "Virtual Desktop Pool" -SaveDelayMinutes 5
  description: |-
    This command changes the save delay setting for the virtual desktop collection named Virtual Desktop Pool that is associated with the RD Connection Broker server named rdcb.contoso.com.
    The command specifies a delay of 5 minutes before the server saves a virtual desktop in the virtual desktop collection that is not in use.
  summary: ""
- title: 'Example 2: Change the user profile disk settings for a virtual desktop collection'
  code: |-
    PS C:\> Set-RDVirtualDesktopCollectionConfiguration -ConnectionBroker "rdcb.contoso.com" -CollectionName "Virtual Desktop Pool" -EnableUserProfileDisks -MaxUserProfileDiskSizeGB 10 -DiskPath "\\RDS-WKS-A27.contoso.com\uvhd"
  description: |-
    This command enables a user profile disk for the virtual desktop collection named Virtual Desktop Pool.
    The command specifies the maximum size of 10 gigabytes for the user profile disk and specifies the path of the user profile disk.
  summary: ""
- title: 'Example 3: Change settings for a virtual desktop collection'
  code: |-
    PS C:\> Set-RDVirtualDesktopCollectionConfiguration -CollectionName "Virtual Desktop Pool" -CollectionDescription "Virtual Desktop Pool created using PowerShell" -RedirectAllMonitors $False -ConnectionBroker "rdcb.contoso.com" -ClientDeviceRedirectionOptions AudioVideoPlayBack,PlugAndPlayDevice
  description: |-
    This command changes configuration settings for the virtual desktop collection named Virtual Desktop Pool.
    The command adds a description to the virtual desktop collection, specifies that the server redirects a single monitor to the remote session, and specifies that Remote Desktop Services redirect AudioVideoPlayBack and PlugAndPlayDevice client devices to the server in this collection.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AutoAssignPersonalVirtualDesktopToUser
  description: |+
    Indicates that the server automatically associates virtual desktops with user accounts when you create a new personal virtual desktop collection.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="RDClientDeviceRedirectionOptions" data-throw-if-not-resolved="False" />
  name: ClientDeviceRedirectionOptions
  description: |+
    Specifies a type of client device to be redirected to an RD Session Host server in this session collection.
    The acceptable values for this parameter are:

    - 0x0000.
    None.
    - 0x0001.
    AudioVideoPlayBack.
    - 0x0002.
    AudioRecording.
    - 0x0004.
    COMPort.
    - 0x0008.
    PlugAndPlayDevice.
    - 0x0010.
    SmartCard.
    - 0x0020.
    Clipboard.
    - 0x0040.
    LPTPort.
    - 0x0080.
    Drive.
    - 0x0100.
    TimeZone.

    You can use binary-or to combine two or more values of this enumeration to specify multiple client device types.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: None, AudioVideoPlayBack, AudioRecording, COMPort, PlugAndPlayDevice, SmartCard, Clipboard, LPTPort, Drive, TimeZone
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CollectionDescription
  description: |+
    Specifies a description for the collection.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CollectionName
  isRequired: true
  description: |+
    Specifies the name of a personal virtual desktop collection.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectionBroker
  description: |+
    Specifies the Remote Desktop Connection Broker (RD Connection Broker) server for a remote desktop deployment.
    If you do not specify a value, the cmdlet uses the fully qualified domain name (FQDN) of the local computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomRdpProperty
  description: |+
    Specifies Remote Desktop Protocol (RDP) settings to include in the .rdp files for all RemoteApp programs and remote desktops that you publish to this collection.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisableUserProfileDisks
  isRequired: true
  description: |+
    Indicates that the server prevents you from using a user profile disk when you configure the collection.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DiskPath
  isRequired: true
  description: |+
    Specifies the path of the user profile disk.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableUserProfileDisks
  isRequired: true
  description: |+
    Indicates that the server enables a user profile disk when you configure the collection.
    A user profile disk stores user profile information in a separate virtual hard disk and saves user profile settings across pooled virtual desktops.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExcludeFilePath
  description: |+
    Specifies an array of file paths that the server excludes when it creates the user profile disk.

    By default, the server creates the standard file and folder paths, for example, Documents and Music.
    Use this parameter with or without the **ExcludeFolderPath** parameter to prevent the server from creating file or folder paths.
    This parameter overrides any identical values that you specify in the **IncludeFilePath** or **IncludeFolderPath** parameters.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExcludeFolderPath
  description: |+
    Specifies an array of folder paths that the server excludes when it creates the user profile disk.

    By default, the server creates the standard file and folder paths, for example, Documents and Music.
    Use this parameter with or without the **ExcludeFilePath** parameter to prevent the server from creating file or folder paths.
    This parameter overrides any identical values that you specify in the **IncludeFilePath** or **IncludeFolderPath** parameters.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: GrantAdministrativePrivilege
  description: |+
    Indicates whether the server grants administrative privileges to the user account that it assigns to a personal virtual desktop.
    This parameter applies only to personal virtual desktop collections.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: IncludeFilePath
  description: |+
    Specifies an array of file paths that the server includes when it creates the user profile disk.

    By default, the server creates the standard file and folder paths, for example, Documents and Music.
    Use this parameter with or without the **IncludeFolderPath** parameter to create file or folder paths.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: IncludeFolderPath
  description: |+
    Specifies an array of folder paths that the server excludes when it creates the user profile disk.

    By default, the server creates the standard file and folder paths, for example, Documents and Music.
    Use this parameter with or without the **IncludeFilePath** parameter to create file or folder paths.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxUserProfileDiskSizeGB
  isRequired: true
  description: |+
    Specifies the maximum size, in gigabytes, for the user profile disk.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RedirectAllMonitors
  description: |+
    Indicates whether the server redirects all client monitors to the remote session.
    Specify $False to redirect a single monitor to the remote session.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RedirectClientPrinter
  description: |+
    Indicates whether the server redirects the client printers to the server printer.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: SaveDelayMinutes
  description: |+
    Specifies the delay, in minutes, before the server saves a virtual desktop that is not in use.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: UserGroups
  description: |+
    Specifies an array of user groups that are authorized to connect to the collection.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: RDMgmt.Set-RDVirtualDesktopCollectionConfiguration
name: Set-RDVirtualDesktopCollectionConfiguration
description: |-
  The **Set-RDVirtualDesktopCollectionConfiguration** cmdlet changes configuration settings for a virtual desktop collection.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: RemoteDesktop.psm1-help.xml
  Module Name: RDMgmt
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/rdmgmt/set-rdvirtualdesktopcollectionconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-RDVirtualDesktopCollectionConfiguration
