### YamlMime:PowershellCmdlet
summary: |-
  Gets an IIS configuration element.
module: WebAdministration
notes: ""
inputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-WebConfiguration
  href: ./Add-WebConfiguration.yml
- text: Backup-WebConfiguration
  href: ./Backup-WebConfiguration.yml
- text: Clear-WebConfiguration
  href: ./Clear-WebConfiguration.yml
- text: Format-List
  href: https://go.microsoft.com/fwlink/p/?LinkId=113302
- text: Restore-WebConfiguration
  href: ./Restore-WebConfiguration.yml
- text: Select-WebConfiguration
  href: ./Select-WebConfiguration.yml
- text: Set-WebConfiguration
  href: ./Set-WebConfiguration.yml
syntaxes:
- >-
  Get-WebConfiguration [-Recurse] [-Metadata] [-Clr <String>] [-Location <String[]>] [-Filter] <String[]>

   [[-PSPath] <String[]>] [<CommonParameters>]
examples:
- title: 'Example 1: Query authentication settings'
  code: |-
    IIS:\> Get-WebConfiguration -Filter "System.WebServer/Security/Authentication/* /*" -Recurse | where {$_.enabled -eq $True} | Format-List
  description: |-
    This command queries for all authentication settings specified under the default website.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Clr
  description: |+
    Specifies the version of the .NET Framework in the form vn.n, such as v4.0 or v2.0.
    The default is v4.0.
    Specify this parameter only when the *PSPath* parameter is set to either Machine or Machine/Webroot.
    If *PSPath* is not set to one of these values and the *Clr* parameter is set, Windows PowerShell ignores the value of *Clr* and returns a warning.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Filter
  isRequired: true
  description: |+
    Specifies the configuration path for which this cmdlet gets the configuration elements.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Location
  description: |+
    Specifies the location of the configuration setting.
    Location tags are frequently used for configuration settings that must be set more precisely than per application or per virtual directory.
    For example, a setting for a particular file or directory could use a location tag.
    Location tags are also used if a particular section is locked.
    In such an instance, the configuration system would have to use a location tag in one of the parent configuration files.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Metadata
  description: |+
    Indicates that the cmdlet returns configuration metadata such as encryption or locking settings.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This path can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in the format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Recurse
  description: |+
    Indicates that this cmdlet returns all elements contained in the specified location and the subsequent hierarchy.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: WebAdministration.Get-WebConfiguration
name: Get-WebConfiguration
description: |-
  The **Get-WebConfiguration** cmdlet gets the Internet Information Services (IIS) configuration element at the specified location.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/get-webconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-WebConfiguration
