### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet retrieves the global settings of the virtual switch from the Network Controller
module: NetworkController
notes: ""
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Following properties can be retrieved for the virtual switch configuration:
    1. Number of interfaces that have Quality of Service (QoS) enabled
    2. Reservation mode for QoS: absolute or Weight
    3. Link speed percentage
    4. Default reservation for QoS
    5. Whether hardware limits are enabled for QoS
    6. Whether hardware reservations are enabled for QoS
    7. Whether software reservations are enabled for QoS
syntaxes:
- >-
  Get-NetworkControllerVirtualSwitchConfiguration [-ConnectionUri <Uri>] [-CertificateThumbprint <String>]

   [-Credential <PSCredential>] [-PassInnerException] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-NetworkControllerVirtualSwitchConfiguration -ConnectionUri https://networkcontroller
  description: ""
  summary: |+
    This example provides the virtual switch configuration of Network Controller, with REST endpoint as https://networkcontroller. The details of the configuration is present in the Properties resource.
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateThumbprint
  description: |+
    Specifies the digital public key X.509 certificate of a user account that has permission to perform this action.This is the certificate thumbprint of the certificate.This thumbprint must also be provided in the *ClientCertificateThumbprint* parameter in the **Install-NetworkController** or **Set-NetworkController** cmdlet so that Network Controller can authorize this user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: ConnectionUri
  description: |+
    Specifies the Uniform Resource Identifier (URI) of the Network Controller, used by all Representational State Transfer (REST) clients to connect to Network Controller.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: Credential
  description: |+
    Specifies a user credential that has permission to perform this action.The default value is the current user.This user must be present in the security group provided in the *ClientSecurityGroup* parameter in the **Install-NetworkController** cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassInnerException
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkController.Get-NetworkControllerVirtualSwitchConfiguration
name: Get-NetworkControllerVirtualSwitchConfiguration
description: |-
  This cmdlet retrieves the global settings of the virtual switch from the Network Controller. This primarily retrieves Quality of Service settings for all virtual switches managed by the Network Controller.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.NetworkController.Powershell.dll-help.xml
  Module Name: NetworkController
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networkcontroller/get-networkcontrollervirtualswitchconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-NetworkControllerVirtualSwitchConfiguration
