### YamlMime:PowershellCmdlet
summary: |-
  Changes the network configuration of a PCSV device.
module: PCSVDevice
notes: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance, Microsoft.Management.Infrastructure.CimInstance#root/Microsoft/Windows/HardwareManagement/MSFT_PCSVDevice" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns a PCSV device object, if you specify the **PassThru** parameter.
links:
- text: Get-PcsvDevice
  href: ./Get-PcsvDevice.yml
- text: Set-PcsvDeviceBootConfiguration
  href: ./Set-PcsvDeviceBootConfiguration.yml
syntaxes:
- >-
  Set-PcsvDeviceNetworkConfiguration [-TimeoutSec <UInt32>] [-IPv4AddressOrigin] <PossibleIPv4Origins>

   [-IPv4Address <String>] [-IPv4DefaultGateway <String>] [-IPv4SubnetMask <String>] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-PcsvDeviceNetworkConfiguration [-TargetAddress] <String> [-Credential] <PSCredential>

   [-ManagementProtocol] <ManagementProtocol> [[-Port] <UInt16>] [-Authentication <Authentication>] [-UseSSL]

   [-SkipCACheck] [-SkipCNCheck] [-SkipRevocationCheck] [-TimeoutSec <UInt32>]

   [-IPv4AddressOrigin] <PossibleIPv4Origins> [-IPv4Address <String>] [-IPv4DefaultGateway <String>]

   [-IPv4SubnetMask <String>] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-PcsvDeviceNetworkConfiguration -InputObject <CimInstance[]> [-IPv4AddressOrigin] <PossibleIPv4Origins>

   [-IPv4Address <String>] [-IPv4DefaultGateway <String>] [-IPv4SubnetMask <String>] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Configure network settings dynamically'
  code: |-
    PS C:\>Set-PcsvDeviceNetworkConfiguration -IPv4AddressOrigin DHCP
  description: |-
    This command configures network settings for the PCSV device.
    The DHCP service updates the IP address, subnet mask and default gateway.
  summary: ""
- title: 'Example 2: Configure network settings statically'
  code: |-
    PS C:\>Set-PcsvDeviceNetworkConfiguration -IPv4AddressOrigin Static -IPv4Address "10.0.1.2" -IPv4DefaultGateway "10.0.0.1" -IPv4SubnetMask "255.255.0.0"
  description: |-
    This command configures network settings for the PCSV device.
    The command specifies the IP address, subnet mask, and default gateway for the device.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Authentication" data-throw-if-not-resolved="False" />
  name: Authentication
  description: |+
    Specifies an authentication method to use for devices managed by WS-Management.
    Do not specify this parameter for devices managed by using IPMI.
    The acceptable values for this parameter are:

    - Basic
    - Digest
    - Default

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: Default, Basic, Digest
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: Credential
  isRequired: true
  description: |+
    Specifies a **PSCredential** object based on a user name and password.
    To obtain a **PSCredential** object, use the **Get-Credential** cmdlet.
    For more information, type `Get-Help Get-Credential`.
    For IPMI devices, specify credentials that correspond to a user with Administrator privileges on the device.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IPv4Address
  description: |+
    Specifies an IPv4 address for the PCSV device.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PossibleIPv4Origins" data-throw-if-not-resolved="False" />
  name: IPv4AddressOrigin
  isRequired: true
  description: |+
    Specifies how the IP address is acquired.
    The acceptable values for this parameter are:

    - Static 
    - DHCP

  defaultValue: None
  position: "3001"
  aliases: ""
  parameterValueGroup: Static, DHCP
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IPv4DefaultGateway
  description: |+
    Specifies an IPv4 default gateway for the PCSV device.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IPv4SubnetMask
  description: |+
    Specifies an IPv4 subnet mask for the PCSV device.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ManagementProtocol" data-throw-if-not-resolved="False" />
  name: ManagementProtocol
  isRequired: true
  description: |+
    Specifies a management protocol used to communicate with a device.
    The acceptable values for this parameter are:

    - WSMAN
    - IPMI

    This cmdlet currently supports only devices that use the IPMI protocol.

  defaultValue: None
  pipelineInput: true
  position: "3"
  aliases: MP
  parameterValueGroup: WSMan, IPMI
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Passthru

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: Port
  description: |+
    Specifies a port on the remote computer to use for the management connection.
    If you do not specify a port, the cmdlet uses the following default ports: 

    - IPMI and WSMAN over HTTP.
    Port 623.
    - WSMAN over HTTPS.
    Port 664.

  defaultValue: None
  pipelineInput: true
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SkipCACheck
  description: |+
    Indicates that the client connects by using HTTPS without validating that a trusted certification authority (CA) signed the server certificate.
    Do not specify this parameter if you specify a value of IPMI for the **ManagementProtocol** parameter.

    Do not specify this parameter unless you can establish trust in another way, such as if the remote computer is part of a network that is physically secure and isolated, or if the remote computer is a trusted host in a Windows Remote Management (WinRM) configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SkipCNCheck
  description: |+
    Indicates that the certificate common name (CN) of the server does not need to match the host name of the server.
    Do not specify this parameter if you specify a value of IPMI for the **ManagementProtocol** parameter.

    Specify this parameter only for managing devices by using WSMAN over HTTPS.
    Be sure to specify this parameter only for trusted computers.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SkipRevocationCheck
  description: |+
    Indicates that the cmdlet skips the revocation check of server certificates.

    Be sure to specify this parameter only for trusted computers.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetAddress
  isRequired: true
  description: |+
    Specifies the name or IP address of the remote hardware device.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: CN, ComputerName, IpAddress
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShellÂ® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: TimeoutSec
  description: |+
    Specifies how long to wait, in seconds, for a response from the remote hardware device.
    After this period, the cmdlet abandons the connection attempt.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: UseSSL
  description: |+
    Indicates that the server connects to the target computer by using SSL.
    WSMAN encrypts all content transmitted over the network.
    Specify this parameter to use the additional protection of HTTPS instead of HTTP.
    If you specify this parameter and SSL is not available on the connection port, the command fails.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: PCSVDevice.Set-PcsvDeviceNetworkConfiguration
name: Set-PcsvDeviceNetworkConfiguration
description: |-
  The **Set-PcsvDeviceNetworkConfiguration** cmdlet changes the network configuration of a Physical Computer System View (PCSV) device.
  You can configure the network settings of a device statically or dynamically, by using the DHCP service.
  If you specify a static network configuration, you must specify the IP address, subnet mask, and default gateway.
  This cmdlet currently supports devices that use the Intelligent Platform Management Interface (IPMI) protocol.
  Changing the network configuration disrupts the out-of-band session, and, therefore, this cmdlet can only be run on an in-band connection.
  To use with an in-band connection, you must have elevated privileges.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: CIM_PhysicalComputerSystemView.cdxml-help.xml
  Module Name: PCSVDevice
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/pcsvdevice/set-pcsvdevicenetworkconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-PcsvDeviceNetworkConfiguration
